baseURL = "https://xcidic.github.io/coding-guidelines/"
languageCode = "en-us"
title = "Xcidic Coding Guideline"
theme = "docdock"

[params]
editURL = "" # https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
noHomeIcon = false # default is false
noSearch = false # default is false
showVisitedLinks = true # default is false
# themeStyle = "theme" # overide base css
themeVariant = "xcidic" # choose theme variant "green", "gold" , "gray", "blue" (default)

[outputs]
home = [ "HTML", "RSS", "JSON"]
